version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: |
            npm i;
      - run: 
          name: "Build app"
          command: |
            env > .env;
            npm run build;
      - sonarcloud/scan:
        sonar_token_variable_name: '9354cee01275ef3ee2d270689bc30bc38c4d5337' 

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
